language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "boilermaker-test";' -U postgres
env:
  global:
    secure: AFavTfP9vTfCsI0JVtz5NE89UsjQLfBTg29EVZngD8SEz6HPQPKYYJAchHcNGMMNzETyeDrqpd3tx3YuNrLiF7FXNisqyKSx41JU4MvCRd9ec8aBnN1Kq8KOhbHlwXwHZh/nEFbHUUTOGHViVGHXGkQIr+c8fCkpmGQ5Eeao6sgb+pIv9AVbTY2Onb4Qx+K+tYyUP0McLRSkXUG9DQ4LFfmA+vUBd5Bdm1NPd03HkrNre8PU2TJOuRLU1c85tWGdFyGtdLsveOmqD29SG05IYO0Tx+Hq6i4KVCLD/RUsxD0ZNNXBBhf6SRupl5UwFj9kzIpBm9kcGLwVlGmJARIoSLiUt8/dETPU3xxOshjylVmjTznQ9ZeHpFOtQBxbT+V32UMzwxHutGP7JfSL4NdC+81mZVYqhhwQK4sqICMk7sMyELeon0UfJKr3LZSP2TGXnZFnNcZo6H1lHJdfn4Iol+fw6fsVQSTLYcb6D/Qtn63kOm6NIewg4iyFVTtenmeW8a6RKbL6T1fSMh99I1nKR5JOUaDIak4yK2TwKOLjVlHeZAeRSMGZWv3KL04LIN/eYhwioFHxxmbaNgA3XVyIX2Wh8KXZSAvLUehhGSdHVMFcWGrysE9sXzqDRZKZIOfiF3r7Cil9W8MicdOIqUzoznKodpxFnNue7Wj2iFRUNZc=
